[package]
name = "clipper"
version = "0.4.0"
edition = "2021"

[dependencies]
scrap = "0.5.0"
spin_sleep = "1.1.1"
gif = "0.12.0"
egui = "0.20.1"
eframe = "0.20.1"
image = "0.24.2"
tokio = { version = "1.25.0", features = ["full"] }